### ISSUE TITLE
HelmReleases admission-provider-aws-runtime/application should use admission helm charts

### ISSUE THREAD

**Issue by mreichardt95** [YAKEcloud/yake#1854]
Flux' HelmReleases like `admission-provider-aws-runtime` currently use `provider-aws` Chart when they should be using the admission Chart, like: https://github.com/gardener/gardener-extension-provider-aws/tree/master/charts/gardener-extension-admission-aws/charts

Currently, the `admission-provider-aws-application/runtime` HelmReleases do not deploy any resources.
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    meta.helm.sh/release-name: extensions
    meta.helm.sh/release-namespace: flux-system
  name: admission-provider-aws-runtime
  namespace: flux-system
spec:
  chart:
    spec:
      chart: provider-aws
      interval: 1m
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: gardener-community-charts
        namespace: flux-system
      version: 1.59.1
  dependsOn:
    - name: admission-provider-aws-application 
```
With https://github.com/gardener/gardener-extension-provider-aws/releases/tag/v1.59.0 the admission part has been seperated into different charts.
