### ISSUE TITLE
Fix upstream webterminal chart installation

### ISSUE THREAD

**Issue by Lappihuan** [YAKEcloud/yake#1908]
With the switch to the upstream webterminal chart the installation does not work anymore.

there is now a new utils-template that also needs to be enabled:
```
utils-templates:
      enabled: true
```

the basevalues could look somewhat like this:
```
    global:
      deployment:
        createCRD: false
        createNamespace: false
        virtualGarden:
          enabled: false
      controller:
        manager:
          config:
            server:
              metrics:
                tlsSecretName: terminal-admission-controller-cert
      admission:
        config:
          server:
            webhooks:
              caBundle: |
                -----BEGIN CERTIFICATE-----
                ...
                -----END CERTIFICATE-----
              tlsSecretName: terminal-admission-controller-cert
```

with for example a Certificate Resource:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: terminal-admission-controller-cert
  namespace: flux-system
spec:
  secretName: terminal-admission-controller-cert
  duration: 87600h #10y
  usages:
    - server auth
  dnsNames:
    - terminal-metrics
    - terminal-metrics.garden
    - terminal-metrics.garden.svc
    - terminal-admission-controller
    - terminal-admission-controller.garden
    - terminal-admission-controller.garden.svc
  issuerRef:
    name: gardener-ca
```

that would also mean the targetPath of the caBundle needs to be changed in the HelmRelease:
```
  valuesFrom:
    - kind: Secret
      name: terminal-admission-controller-cert
      valuesKey: tls.crt
      targetPath: global.admission.config.server.webhooks.caBundle
      optional: true
```
as well as the targetNamespace in both the runtime and the application releases:
```
targetNamespace: garden
```
after all this i can install the chart but in the terminal-controller-manager pod i get this log while it CrashLoops:
```
{"level":"info","ts":"2025-01-24T10:02:36Z","logger":"setup","msg":"setting up webhook server"}
{"level":"info","ts":"2025-01-24T10:02:36Z","logger":"setup","msg":"registering webhooks to the webhook server"}
{"level":"info","ts":"2025-01-24T10:02:36Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-terminal"}
{"level":"info","ts":"2025-01-24T10:02:36Z","logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-terminal"}
{"level":"error","ts":"2025-01-24T10:02:36Z","logger":"setup","msg":"unable to add project namespace field indexer","error":"failed to add indexer for spec.namespace to Project Informer: no matches for kind \"Project\" in version \"core.gardener.cloud/v1beta1\"","stacktrace":"main.main\n\t/workspace/main.go:182\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}
stream closed EOF for garden/terminal-controller-manager-5797586f6b-hl7cg (manager)
```

the `Project` CRD seems to be missing somehow
