### ISSUE TITLE
Add pod labels to ingress-nginx

### ISSUE THREAD

**Issue by JensAc** [YAKEcloud/yake#389]
We need the following labels for ingress-nginx in order to prevent problems with network policies: 
```yaml
controller:
  ...
  podLabels:
    app: nginx-ingress
    component: controller
```
